### ISSUE TITLE
US8 - Implementierung des VaultODVImporter Plugins

### ISSUE THREAD

**Issue by lucasbuschlinger** [lucasbuschlinger/BachelorPraktikum#10]
Beschreibung:
-
Der VaultODVImporter importiert ODV Daten von OpenDiabetes und übersetzt diese in VaultEntries. Dies wird als Plugin bereitgestellt.

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

Akzeptanzkriterium:
-
Das VaultODVImporter Plugin lässt sich laden und auf die Methoden zugreifen. OpenDiabetes ODV Daten werden korrekt importiert und in VaultEntries überführt.

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

(Geschätzter) Aufwand:
-
5SP - Nur die OpenDiabetes ODV spezifische Methoden müssen implementiert werden. 

[//]: # "------------Hier drüber eine Zeile frei!------------"
[//]: # "Zu Project und Milestone (Sprint) zugewiesen?"

**Comment by ghtina** [comment]
time spent: 2.5 hours
done with #13
