### ISSUE TITLE
Libs für Plugins in die einzelnen Plugins kopieren

### ISSUE THREAD

**Issue by ocastx** [lucasbuschlinger/BachelorPraktikum#105]
Beschreibung:
-
Derzeit sind alle Libraries die von Plugins benötigt werden in dem lib root Ordner. Wenn man aber ein Plugin nicht braucht wird das Projekt aber mit all den Libraries ausgeliefert obwohl es diese nicht benötigt.

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

Akzeptanzkriterium:
-
Das Ant Skript muss so angepasst werden, dass es die Libs aus dem Plugin automatisch bezieht und in das Projekt kopiert wenn das Plugin benötigt wird.

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

(Geschätzter) Aufwand:
-
3 SP

[//]: # "------------Hier drüber eine Zeile frei!------------"
[//]: # "Zu Project und Milestone (Sprint) zugewiesen?"

**Comment by lucasbuschlinger** [comment]
Soweit ich das weiß, kann man in PF4J die Libraries auch im plugin ZIP in /libs legen und diese werden dann in den Classpath aufgenommen, muss mal schauen wie es ist, wenn mehrere Plugins die gleiche Lib verwenden...

**Comment by Magnusgaertner** [comment]
wird in #123  gelöst
