### ISSUE TITLE
RawEntry entfernen

### ISSUE THREAD

**Issue by ocastx** [lucasbuschlinger/BachelorPraktikum#107]
Beschreibung:
-
RawEntry Klasse kann entfernt werden.

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

Akzeptanzkriterium:
-
-

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

(Geschätzter) Aufwand:
-
1 SP

[//]: # "------------Hier drüber eine Zeile frei!------------"
[//]: # "Zu Project und Milestone (Sprint) zugewiesen?"

**Comment by lucasbuschlinger** [comment]
Done
