### ISSUE TITLE
Wiki Seite Interfaces

### ISSUE THREAD

**Issue by ocastx** [lucasbuschlinger/BachelorPraktikum#115]
Beschreibung:
-
Eine Wiki Seite für die Interfaces, was sie bereitstellen und wie man sie zum Plugin schreiben benutzt.

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

Akzeptanzkriterium:
-

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

(Geschätzter) Aufwand:
-
4 SP

[//]: # "------------Hier drüber eine Zeile frei!------------"
[//]: # "Zu Project und Milestone (Sprint) zugewiesen?"

**Comment by lucasbuschlinger** [comment]
Take a look at [this](https://github.com/lucasbuschlinger/BachelorPraktikum/wiki/Interfaces) @ocastx 
Sieht ziemlich gut aus, 👍 @MarkusHenkel 

Done?

**Comment by ocastx** [comment]
Jep ist in Ordnung, closed
