### ISSUE TITLE
Wiki Seite VaultEntry

### ISSUE THREAD

**Issue by ocastx** [lucasbuschlinger/BachelorPraktikum#116]
Beschreibung:
-
Eine Wiki Seite für die Klassen aus dem container package. Was sie tun und wie man sie im Plugin benutzt.

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

Akzeptanzkriterium:
-

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

(Geschätzter) Aufwand:
-
5 SP

[//]: # "------------Hier drüber eine Zeile frei!------------"
[//]: # "Zu Project und Milestone (Sprint) zugewiesen?"

**Comment by lucasbuschlinger** [comment]
Done, wanna check @ocastx ?

**Comment by lucasbuschlinger** [comment]
Irgendwer das mal durchgelesen?

**Comment by ocastx** [comment]
Jep, das hatte ich schon gemacht, aber noch nicht das Ticket geschlossen :D. Closed
