### ISSUE TITLE
Hilfeseite für OdvDbJsonExporter

### ISSUE THREAD

**Issue by ghtina** [lucasbuschlinger/BachelorPraktikum#118]
Beschreibung:
-
Für das Plugin OdvDbJsonExporterwird eine Hilfeseite benötigt

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

Akzeptanzkriterium:
-
Die Methode getHelp() im Plugin gibt einen .md/html formatierten String zurück der dem Benutzer erklärt was das Plugin macht, was es für Daten akzeptiert, welche Einstellmöglichkeiten man hat.

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

(Geschätzter) Aufwand:
-
4 SP

**Comment by ghtina** [comment]
# OdvDbJsonExporter
ver 0.0.1
Classification: Exporter

Overview
-----
The OdvDbJsonExporter is an exporter plugin which exports data from the database.

Data example
-----

Configuration
-----
The Sample plugin offers the following configuration options:

| key  | value | description | required |
| ------------- | ------------- |  ------------- | ------------- |
| compatiblePlugins | PluginA, PluginB, PluginC | A list of plugins that are compatible with the OdvDbJsonExporter plugin, separated by commas. | x


Required Plugins
-----
The OdvDbJsonExporter does not require any other plugins.

**Comment by ocastx** [comment]
Done by #133
