### ISSUE TITLE
Wiki Seite Getting started

### ISSUE THREAD

**Issue by ocastx** [lucasbuschlinger/BachelorPraktikum#137]
Beschreibung:
-
Für Entwickler ist es derzeit schwierig sich in das Projekt einzufinden nachdem sie es heruntergeladen werden. In einem kurzen Guide sollte beschrieben werden wie man das Projekt korrekt aufsetzt mit der Überleitung ein eigenes Plugin zu schreiben.

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

Akzeptanzkriterium:
-
Eine Wiki Seite mit einem detaillierten Getting started Guide.

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

(Geschätzter) Aufwand:
-
4 SP

[//]: # "------------Hier drüber eine Zeile frei!------------"
[//]: # "Zu Project und Milestone (Sprint) zugewiesen?"

**Comment by ocastx** [comment]
Please review https://github.com/lucasbuschlinger/BachelorPraktikum/wiki/Getting-started @lucasbuschlinger

**Comment by ocastx** [comment]
Also revamped wiki intro page https://github.com/lucasbuschlinger/BachelorPraktikum/wiki

**Comment by lucasbuschlinger** [comment]
Nicely done 👍
