### ISSUE TITLE
Wiki Seite PluginManager

### ISSUE THREAD

**Issue by ocastx** [lucasbuschlinger/BachelorPraktikum#141]
Beschreibung:
-
Um das Projekt besser zu verstehen sollte es eine Wiki Seite für den Plugin Manager geben der die Funktionsweise beschreibt.

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

Akzeptanzkriterium:
-
Eine neue Wiki Seite die detailliert die Funktionsweise des Plugin Managers beschreibt so dass auch neue Entwickler damit arbeiten können.

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

(Geschätzter) Aufwand:
-
2 SP

[//]: # "------------Hier drüber eine Zeile frei!------------"
[//]: # "Zu Project und Milestone (Sprint) zugewiesen?"

**Comment by ocastx** [comment]
@Magnusgaertner status? Soll das jemand anderes machen falls keine Zeit mehr?

**Comment by lucasbuschlinger** [comment]
https://github.com/lucasbuschlinger/BachelorPraktikum/wiki/Using-the-plugins-‐-OpenDiabetesPluginManager

**Comment by lucasbuschlinger** [comment]
Frage ist nur, ob das done ist

**Comment by Magnusgaertner** [comment]
https://github.com/lucasbuschlinger/BachelorPraktikum/wiki/Using-the-plugins-%E2%80%90-OpenDiabetesPluginManager
