### ISSUE TITLE
US9 - Konfigurationsdaten einlesen

### ISSUE THREAD

**Issue by Magnusgaertner** [lucasbuschlinger/BachelorPraktikum#18]
Beschreibung:
-
Plugins (Importer und Exporter) haben verschiedenste Einstellungen, die vom Benutzer änderbar sein sollen. Ein Reader wird benötigt der Konfigurationsdateien in liest und den einzelen Plugins zur Verfügung steht. Eine Konfigurationsdatei soll dabei in einem möglichst abstrakten Format übergeben werden können.

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

Akzeptanzkriterium:
-
Ein ImporterPlugin kann durch Parameter mit einem bestimmten, eindeutigen Namen (Key)  aus einer Konfigurationsdatei konfiguriert werden. Dabei wird die Konfiguration **nicht** durch die im Importer Interface vorgesehenen Methode "loadConfiguration(String filePath)" übergeben. Stattdessen ist die Methode zu loadConfiguration(InputSteam config) geändert. 

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

(Geschätzter) Aufwand:
-
10SP

[//]: # "------------Hier drüber eine Zeile frei!------------"
[//]: # "Zu Project und Milestone (Sprint) zugewiesen?"

**Comment by ghtina** [comment]
done by #27 closing this
