### ISSUE TITLE
US10 - CSVValidator, smart delimiter selection

### ISSUE THREAD

**Issue by Magnusgaertner** [lucasbuschlinger/BachelorPraktikum#19]
Beschreibung:
-
Es existieren verschiedenste CSV dateiformate, die über Importer eingelesen werden. Dabei treten verschiedene Delimiter auf die die Einträge in der Datei voneinander Sortieren. Ist dieser Delimiter konstant gewählt, dann kann der Importer im Falle eines anderen Delimiters die Datei nichtmehr lesen. Dieser Umstand soll vermieden werden indem CSV Importer selbstständig gängige Delimiter ausprobieren um eine Datei auszulesen.

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

Akzeptanzkriterium:
-
CSVImporter wählen automatisch das richtige Delimiter Zeichen aus und Parsen die Datei nach diesem Delimiter. Es werden gängige Delimiter Zeichen: ',', ';', '\t' unterstützt und die Zeichen können nach Bedarf durch Hinzufügen weiterer Zeichen zu einer Liste möglicher Delimiter erweitert werden.

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

(Geschätzter) Aufwand:
-
10SP

[//]: # "------------Hier drüber eine Zeile frei!------------"
[//]: # "Zu Project und Milestone (Sprint) zugewiesen?"

**Comment by lucasbuschlinger** [comment]
Done by #39
