### ISSUE TITLE
Anleitung zur Erstellung eines Plugins für OpenDiabetes

### ISSUE THREAD

**Issue by Magnusgaertner** [lucasbuschlinger/BachelorPraktikum#20]
Beschreibung:
-
OpenDiabetes wird nie vollständig entwickelt sein, denn es wird immer Dateiformate geben, die noch nicht unterstützt werden. Deshalb soll ein Tutorial erstellt werden, wie eine solche Erweiterung für OpenDiabetes erstellt werden kann.

**Comment by lucasbuschlinger** [comment]
Wie stehts hier so? Wäre nice, wenn man das in der Konversation mit der ML-Gruppe hätte :) @freaklovesmango
