### ISSUE TITLE
US11 - CSVFileExporter

### ISSUE THREAD

**Issue by Magnusgaertner** [lucasbuschlinger/BachelorPraktikum#21]
Beschreibung:
-
Der CSVFileExporter exportiert Datenbankeinträge in eine CSV Datei. 

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

Akzeptanzkriterium:
-

Das CSVFileExporter Plugin lässt sich laden und auf die Methoden zugreifen. Datenbank Einträge werden korrekt in eine CSV Datei exportiert.

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

(Geschätzter) Aufwand:
-
10SP - Da dies das erste Exporter Plugin ist

[//]: # "------------Hier drüber eine Zeile frei!------------"
[//]: # "Zu Project und Milestone (Sprint) zugewiesen?"

**Comment by lucasbuschlinger** [comment]
Der CSVExporter ist kein Plugin, habe nachgefragt.

**Comment by lucasbuschlinger** [comment]
Erledige das zusammen mit #25 
Das enthält jedoch alle Funktionalität die alle Exporter verwenden

**Comment by lucasbuschlinger** [comment]
Mit #25 erledigt in #28
