### ISSUE TITLE
US17 - Implementierung eines Webcrawlers für weitere Medtronic Daten als Plugin

### ISSUE THREAD

**Issue by lucasbuschlinger** [lucasbuschlinger/BachelorPraktikum#37]
Beschreibung:
-
Das genannte Plugin Crawled die Website carelink.minimed.eu nach Daten für den MedtronicImporter. Zweck ist hiermit weitere Daten für die OpenDiabetes Website zu erhalten

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

Akzeptanzkriterium:
-
Das Plugin lässt sich laden. Der Crawler loggt sich mit hinterlegten Daten bei der Website ein und läd Dateien herunter. Diese werden anschließend mit dem MedtronicImporter importiert.

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

(Geschätzter) Aufwand:
-
10SP - Aufgrund das dies eine unbekannte Art an Importer ist und dies in die bestehende Codebasis integriert werden muss

[//]: # "------------Hier drüber eine Zeile frei!------------"
[//]: # "Zu Project und Milestone (Sprint) zugewiesen?"

**Comment by ocastx** [comment]
Braucht noch Änderungen, vor allem das weitergeben der Daten an den MedtronicImporter und das Interface muss noch angepasst werden.

**Comment by ocastx** [comment]
Also das weitergeben an das Medtronic Importer Plugin ist implementiert. Ich warte gerade noch auf die Rückmeldung von Jens bzgl. der User/Passwort Sachen wo die gespeichert werden sollen und dann kann das nochmal reviewed werden

**Comment by ocastx** [comment]
Also die Credentials sollen übergeben werden beim aufruf des importers, sprich wir bräuchten ein eigenes Interface für den Importer, richtig @lucasbuschlinger ?

**Comment by lucasbuschlinger** [comment]
Puh scheint so, aber ist halt semi-geil

**Comment by ocastx** [comment]
Hm ja, wüsste auch nicht wer das dann wie reingibt über die GUI. Ansonsten kann man halt erstmal so das Plugin nicht benutzen mit GUI

**Comment by lucasbuschlinger** [comment]
Stimmt, das wäre ja auch irgendwie komisch dafür ein neues Fenster zu öffnen
