### ISSUE TITLE
Refactoring/Aufräumen im Code

### ISSUE THREAD

**Issue by lucasbuschlinger** [lucasbuschlinger/BachelorPraktikum#42]
Beschreibung:
-
Dies wird wohl ein Running Task, der der Umsetzung von besprochenem Refactoring/Aufräumen im Code dient

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

Akzeptanzkriterium:
-
Besprochene Sachen gelöst

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

(Geschätzter) Aufwand:
-
...

[//]: # "------------Hier drüber eine Zeile frei!------------"
[//]: # "Zu Project und Milestone (Sprint) zugewiesen?"

**Comment by lucasbuschlinger** [comment]
Für Iteration 5 sind zu tun:
- [ ] (VaultDao) unbenutzt Methoden rausnehmen (auskommentieren)
- [ ] Medtronic Header auf private stellen
- [ ] GoogleFit Header auf private stellen
- [ ] MySugr Header auf private stellen
- [ ] SonySWR21 Header auf private stellen
- [ ] Null check auf Try Catch umbauen MedtronicImport etc. um FindBugs issue zu resolven

**Comment by lucasbuschlinger** [comment]
Ich schlage vor dafür ebenfalls den bugfix Branch zu nutzen

**Comment by lucasbuschlinger** [comment]
@MarkusHenkel kannst du abhaken, was du erledigt hast?
Wäre gut zu wissen, dann könnte man eventuell bald einen PullRequest starten :)

**Comment by ghost** [comment]
- [x] (VaultDao) unbenutzte Methoden rausnehmen (auskommentieren)
- [x] Medtronic Header auf private stellen
- [x] GoogleFit Header auf private stellen
- [x] MySugr Header auf private stellen
- [x] SonySWR21 Header auf private stellen
- [x] Null check auf Try Catch umbauen (MedtronicImporter etc.), um FindBugs issue zu resolven

Die Aufgaben für Issue 42 sind erledigt, ich war mir allerdings nicht sicher, ob ich hier noch anderes fixen soll oder das nach dem pull request mache. Zum Beispiel wird im MedtronicImporter bei ungültigem Header / Timestamp was ins log geschrieben, bei den meisten anderen hingegen nicht. Aber das kann man ja eigentlich auch später noch ändern.

**Comment by lucasbuschlinger** [comment]
Ja passt, das waren ja jetzt erst einmal die Sachen, die wir besprochen hatten. Ich schaue mal wegen dem Log, bin ja eh an den Validatoren/Importern

**Comment by lucasbuschlinger** [comment]
Done with #49 (for now)
