### ISSUE TITLE
TODOs im Code durchgehen

### ISSUE THREAD

**Issue by lucasbuschlinger** [lucasbuschlinger/BachelorPraktikum#43]
Beschreibung:
-
Alle im Code vorhandenen ToDo werden durchgegangen und zusammengestellt. Eine Liste mit offenen ToDos wird an AG geschickt und dann werden diese gelöst.

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

Akzeptanzkriterium:
-
Alle offenen ToDos mit AG besprochen und anschließend gelöst

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

(Geschätzter) Aufwand:
-
...

[//]: # "------------Hier drüber eine Zeile frei!------------"
[//]: # "Zu Project und Milestone (Sprint) zugewiesen?"

**Comment by ghtina** [comment]
using branch bugfix

**Comment by ghtina** [comment]
there are three open TODOs, but don't know how to resolve them
the other TODOs are resolved
waiting for the refactoring so that we can start a pull request

**Comment by lucasbuschlinger** [comment]
done with #49 (for now)
