### ISSUE TITLE
Plugin Tutorials

### ISSUE THREAD

**Issue by lucasbuschlinger** [lucasbuschlinger/BachelorPraktikum#45]
Beschreibung:
-
Es werden Tutorials mit minimalem Build Script erstellt, anhand derer das Implementieren und Bauen von Plugins demonstriert wird.

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

Akzeptanzkriterium:
-
Es ist mit möglich mit den gängigen IDEs mit dem Tutorial und dem zugehörigen Code Plugins zu bauen.

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

(Geschätzter) Aufwand:
-
....

[//]: # "------------Hier drüber eine Zeile frei!------------"
[//]: # "Zu Project und Milestone (Sprint) zugewiesen?"

**Comment by lucasbuschlinger** [comment]
Noch immer gewünscht
@Magnusgaertner du hast da doch mal was gemacht, existiert das noch?

**Comment by Magnusgaertner** [comment]
https://github.com/Magnusgaertner/ExporterPluginOpenDiabetes
existiert, es müsste die OpenDiabetes Jar geupdated werden aber sonst passts...

**Comment by Magnusgaertner** [comment]
ich kann mich nochmal dran setzen und das hübsch machen ;)

**Comment by Magnusgaertner** [comment]
https://github.com/lucasbuschlinger/BachelorPraktikum/wiki/Creating-your-own-Importer
und das hier halt im wiki

**Comment by ocastx** [comment]
Resolved by: https://github.com/lucasbuschlinger/BachelorPraktikum/wiki/Creating-Plugins and https://github.com/lucasbuschlinger/BachelorPraktikum/wiki/Creating-Plugins 

Thanks @Magnusgaertner 👏
