### ISSUE TITLE
Hilfeseite für sony importer

### ISSUE THREAD

**Issue by Magnusgaertner** [lucasbuschlinger/BachelorPraktikum#59]
Beschreibung:
-
Für das Plugin sony importer wird eine Hilfeseite benötigt

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

Akzeptanzkriterium:
-
Die Methode getHelp() im Plugin gibt einen .md/html formatierten String zurück der dem Benutzer erklärt was das Plugin macht, was es für Daten akzeptiert, welche Einstellmöglichkeiten man hat.

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

(Geschätzter) Aufwand:
-
4 SP

**Comment by ghost** [comment]
# SonySWR12Importer
Version: 0.0.1
Classification: Importer

Overview
-----
The SonySWR12Importer plugin is an importer plugin which imports SonySWR12 data in the .csv format.

Data example
-----
The .csv format is commonly used to represent multivariate data. Every data point's values are separated by a delimiter. However, this delimiter is not standardized which means that it can vary between files. You can find more information on the .csv format here: https://en.wikipedia.org/wiki/Comma-separated_values  

Configuration
-----
The SonySWR12Importer plugin offers the following configuration options:

| key  | value | description | required |
| ------------- | ------------- |  ------------- | ------------- |
| compatiblePlugins | PluginA, PluginB, PluginC | A list of plugins that are compatible with the SonySWR12Importer plugin, separated by commas. | x

Required Plugins
-----
 - The SonySWR12Importer does not require any other plugins.

**Comment by ocastx** [comment]
Done by #133
