### ISSUE TITLE
Hilfeseite für odvdbjson importer

### ISSUE THREAD

**Issue by Magnusgaertner** [lucasbuschlinger/BachelorPraktikum#60]
Beschreibung:
-
Für das Plugin odvdbjson importer wird eine Hilfeseite benötigt

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

Akzeptanzkriterium:
-
Die Methode getHelp() im Plugin gibt einen .md/html formatierten String zurück der dem Benutzer erklärt was das Plugin macht, was es für Daten akzeptiert, welche Einstellmöglichkeiten man hat.

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

(Geschätzter) Aufwand:
-
4 SP

**Comment by ghost** [comment]
# ODVDBJsonImporter
Version: 0.0.1
Classification: Importer

Overview
-----
The ODVDBJsonImporter plugin is an importer plugin which imports ODVDB data in the .json format.

Data example
-----
You can find more information on the .json format here: https://en.wikipedia.org/wiki/JSON 

Configuration
-----
The ODVDBJsonImporter plugin offers the following configuration options:

| key  | value | description | required |
| ------------- | ------------- |  ------------- | ------------- |
| compatiblePlugins | PluginA, PluginB, PluginC | A list of plugins that are compatible with the ODVDBJsonImporter plugin, separated by commas. | x

Required Plugins
-----
 - The ODVDBJsonImporter does not require any other plugins.

**Comment by ocastx** [comment]
Done by #133
