### ISSUE TITLE
Hilfeseite für VaultCSVExporter

### ISSUE THREAD

**Issue by Magnusgaertner** [lucasbuschlinger/BachelorPraktikum#66]
Beschreibung:
-
Für das Plugin vaultcsv exporter wird eine Hilfeseite benötigt

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

Akzeptanzkriterium:
-
Die Methode getHelp() im Plugin gibt einen .md/html formatierten String zurück der dem Benutzer erklärt was das Plugin macht, was es für Daten akzeptiert, welche Einstellmöglichkeiten man hat.

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

(Geschätzter) Aufwand:
-
4 SP

**Comment by ghtina** [comment]
# VaultCSVExporter
ver 0.0.1
Classification: Exporter

Overview
-----
The VaultCSVExporter is an exporter plugin which exports data from the database.

Data example
-----

Configuration
-----
The Sample plugin offers the following configuration options:

| key  | value | description | required |
| ------------- | ------------- |  ------------- | ------------- |
| compatiblePlugins | PluginA, PluginB, PluginC | A list of plugins that are compatible with the VaultCSVExporter plugin, separated by commas. | x

Required Plugins
-----
The VaultCSVExporter does not require any other plugins.

**Comment by ocastx** [comment]
Done by #133
