### ISSUE TITLE
US22 - Struktur für Hilfeseiten

### ISSUE THREAD

**Issue by Magnusgaertner** [lucasbuschlinger/BachelorPraktikum#70]
Beschreibung:
-
Es werden für alle Plugins Hilfeseiten benötigt. Es soll eine allgemeine Struktur für die Hilfeseiten geben um die Hilfeseiten der einzelnen Plugins zu vereinheitlichen. Zugleich wird damit der Aufwand für einzelne Hilfeseiten verringert.

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

Akzeptanzkriterium:
-
Es existiert ein template für eine Hilfeseite mit dem die konkreten Hilfeseiten für die Plugins geschrieben werden können.

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

(Geschätzter) Aufwand:
-
4 SP

**Comment by ocastx** [comment]
Eine erste Version hab ich mal unten angehängt, gerne erweiter/änderbar.


# Sample Plugin
ver 1.0.1
Classification: Importer

Overview
-----
Sample plugin is an importer plugin which imports data in the sample.smpl format.

Data example
-----
The sample.smpl format ist a format used by the Sample Corp. and example can be found here: http://example.com/sample.smpl

Configuration
-----
The Sample plugin offers the following configuration options:

| key  | value | description | required |
| ------------- | ------------- |  ------------- | ------------- |
| fromDate | DD.MM.YYYY | The date from when the data in the provided smple file should be imported | x
| toDate | DD.MM.YYYY | The date until when the data in the provided smpl file should be imported | 

Required Plugins
-----
 - CSVImporterPlugin (http://example.com/CSVImporter)

**Comment by ocastx** [comment]
Die Struktur geht soweit von Jens in Ordnung. Mit dieser sollte jeweils eine Hilfeseite für Englisch und Deutsch für jedes Plugin erstellt werden. Englisch ist erstmal wichtiger, deutsch optional.
Unten findet sich auch nochmal das deutsche Template.

# Sample Plugin
ver 1.0.1
Klassifikation: Importer

Übersicht
-----


Beispiel Datensatz
-----


Konfiguration
-----
Das Sample Plugin bietet folgende Konfigurationsmöglichkeiten:

| schlüssel  | wert | beschreibung | notwendig
| ------------- | ------------- |  ------------- | ------------- |

Benötigte Plugins 
-----
 - CSVImporterPlugin (http://example.com/CSVImporter)
