### ISSUE TITLE
US23 - Portieren der vorhandenen Interpreter als Plugin

### ISSUE THREAD

**Issue by Magnusgaertner** [lucasbuschlinger/BachelorPraktikum#71]
Beschreibung:
-
Die bereits vorhandenen Interpreter werden als Plugin dem Projekt hinzugefügt

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

Akzeptanzkriterium:
-

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

(Geschätzter) Aufwand:
-
25 SP

**Comment by lucasbuschlinger** [comment]
Concluded by #90
