### ISSUE TITLE
add compatibility list among plugins in plugin config

### ISSUE THREAD

**Issue by Magnusgaertner** [lucasbuschlinger/BachelorPraktikum#76]

**Comment by lucasbuschlinger** [comment]
Über plugin.properties in ZIP oder die zusätzliche Config?
Ich glaub das geht nur über die zusätzliche

**Comment by Magnusgaertner** [comment]
es wird über die properties/<>.properties gemacht. key ist "compatiblePlugins"

**Comment by ocastx** [comment]
kann geschlossen werden oder @Magnusgaertner ?
