### ISSUE TITLE
US27 - PluginManagement System

### ISSUE THREAD

**Issue by Magnusgaertner** [lucasbuschlinger/BachelorPraktikum#85]
Beschreibung:
-
Das Projekt organisiert Plugins verschiedener Typen. Es sollen alle Plugins zentral und möglichst einfach angesprochen werden können.

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

Akzeptanzkriterium:
-
Es existiert eine OpenDiabetesPluginManager Klasse die es ermöglicht, einzelne plugins zu verwenden, Listen von Plugins verschiedener Typen zurückgibt, Plugins automatisch läd und initialisiert. Außerdem kann abgefragt werden zu welchen Plugins ein Plugin kompatibel ist. 

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

(Geschätzter) Aufwand:
-
12.5 SP

[//]: # "------------Hier drüber eine Zeile frei!------------"
[//]: # "Zu Project und Milestone (Sprint) zugewiesen?"

**Comment by lucasbuschlinger** [comment]
Done by #84
