### ISSUE TITLE
Tasks - Iteration 8

### ISSUE THREAD

**Issue by lucasbuschlinger** [lucasbuschlinger/BachelorPraktikum#92]
- [x] - PlotterExporter: Pfad zu Script nicht hardgecoded
- [x] - PlotterExporter: Verwenden von $TEMP
- [x] - Medtronic Crawler: Verwenden von $TEMP
- [x] - ExerciseInterpreter: Type auf Exercise_Other und benötigten Code un-auskommentieren
- [x] - VaultODV raus
- [x] - MiBand: Gson case insensitive
- [x] - Repo Cleanup
- [ ] - Plotteria mit eigenen Exports ausprobieren
- [x] - Cleanup Properties (Duplikate)
- [ ] - Fehler in den Hauptmethoden an die GUI notify-en

**Comment by lucasbuschlinger** [comment]
MiBand lässt sich nicht case insensitive machen, da die Feldnamen im JSON nicht konsistent sind (Objekt = UpperCamelcase, dessen inhalt lowerCamelcase...)

Edit: Geht doch, mit Jackson

**Comment by ghost** [comment]
Ich hab mal die status notifications bei Fehlern in importData bzw. exportDataToFile hinzugefügt.

Ich versteh aber nicht ganz, warum im CSVImporter in der Methode processImport true returned wird, auch wenn es ne Exception gab (die dann gefangen wurde). Könnte doch auch sein, dass es ne ParseException gibt und dann nicht alles richtig processed wird. Sollte man in dem Fall nicht false returnen?

**Comment by ocastx** [comment]
Beim repo waren doch nicht mehr die reports drin, das war ein alter branch. Denke ansonsten gibts nichts aufzuräumen

**Comment by ocastx** [comment]
Bzgl. Plotteria warte ich auf die Antwort von Jens, ob er weiß warum das Skript nicht geht.
Mit normalen VaultCSV Daten gibt es nur 0,00% aus und das plot ist 1x1 Pixel groß.

@lucasbuschlinger was ist mit Cleanup Properties (Duplikate) gemeint?

**Comment by lucasbuschlinger** [comment]
https://github.com/lucasbuschlinger/BachelorPraktikum/tree/master/properties

Hier sind ein paar Duplikate drin, das hab ich gemeint @ocastx

**Comment by lucasbuschlinger** [comment]
@MarkusHenkel : gut erkannt mit dem fehlenden negativen Return 👍 
Lass mal mit dem Merge bis morgen warten, eine alternative wäre nämlich, dass die GUI einfach das Log auch bekommt und dann halt bei einem gewissen Level einen Fehler anzeigt, wäre aber eigentlich auch für das den Weg über notifyStatus()

**Comment by lucasbuschlinger** [comment]
Das mit dem Properties wird im cleanup Branch erledigt

**Comment by ocastx** [comment]
kann dafür ein PR erstellt werden?

**Comment by lucasbuschlinger** [comment]
Hab einen für Cleanup erstellt @ocastx

**Comment by lucasbuschlinger** [comment]
Ich mach nen neuen Thread für die neue Iteration auf
