### ISSUE TITLE
Task - Iteration 9

### ISSUE THREAD

**Issue by lucasbuschlinger** [lucasbuschlinger/BachelorPraktikum#99]
- [x] - Check & Review: Fehler in den Hauptmethoden an die GUI notify-en: #96 
- [x] - Plotteria Check (Matplotlib korrekte Version...)
- [x] - #70 (Basti)
- [x] - Hilfeseiten (DE/ENG) für Plugins
- [x] - Update Checkstyle-Rules (Methodenlänge)
- [x] - Automatische JavaDoc Generation und Veröffentlichung über GitHub Pages (Basti)
- [x] - Dateipfad über Parameter der Methoden übergeben, nicht explizit setzten (Importer/Exporter)
- [x] - Import: List<VaultEntry> anstatt boolean zurückgeben (?)
- [x] - getHelpFilePath() in der Hierarchie nach oben (assigned by Magnus)
- [x] - Generell schauen, ob getter/setter nötig sind (Basti)
- [x] - getImportedRawData rausnehmen (Basti)
- [x] - Generell schauen, ob man Methoden in der Hierarchie noch nach oben ziehen kann (siehe ausführliche taskliste in den Kommentaren)
- [ ] - Interface für Filter (Absprache mit ML?) (assigned by Magnus)
- [x] - Unit tests fixen (assigned by Magnus)
- [x] - FindBugs Sachen fixxen
- [x] - Exceptions werfen ansatt notify für GUI

**Comment by Magnusgaertner** [comment]
bitte alles in cleanup bearbeiten ^^

**Comment by ocastx** [comment]
Dann markiert auch mal die Punkte die schon erledigt wurden damit wir wissen was noch offen ist

**Comment by ocastx** [comment]
Mit der matplotlib 2.0.0 hat das plotting skript funktioniert 👍

**Comment by Magnusgaertner** [comment]
getHelpFilePath wurde vollständig aus den plugins entfernt und eine entsprechende methode im Pluginmanager geschrieben, die den pfad zur hilfeseite bereitstellt und falls nicht vorhanden einen pfad zu einem default
"dieses plugin hat leider noch keine Hilfeseite" 
übergibt, diese ist unter resources/defaultHelp.md zu finden. Hilfeseiten müssen help.md heißen und im untersten package, also da wo auch die jew. plugin.properties liegt liegen. Das build script schiebt sie dann in den plugin root folder, also in export/<pluginIDblabla>/help.md

**Comment by Magnusgaertner** [comment]
Zur Restrukturierung (branch: restructuring):
- [x] setEntries im Exporter muss refactored werden, wird nur im SliceLayoutExporter genutzt, siehe weiter unten

- [x] preprocessing if needed braucht eine standart not needed implementierung damit nicht alle das leer überschreiben müssen (done, kein einziger importer benutzt aktuell preprocessing) 

- [x] MedtronicCrawler wird gesondert behandelt

- [x] Im MySugrCSVImporter Max_Header_lines_Scan ist unused

- [x] AbstractFileImporter#importData()  muss raus, dafür muss der ODVImporter angepasst werden(sollte so wie es jetzt ist nicht funktionieren)

- [x] csvImporter preprocessingIfNeeded ist völlig nutzlos, weil einfach redeklariert wird was im AbstractFileImporter steht 

- [x] DiaryInterpreter ist nicht implementiert und kann daher raus

- [ ] generell sind die InterpreterConfig attribute mehr argumente zum interpretieren --> sollten stateless sein, gleiches problem wie ML gruppe mit Filtern

- [x] NonInterpreter package ist leer, kann daher auch raus

- [ ] alle Plugins sollten durchgegangen werden und die notifications geprüft ergänzt werden

- [x] Der DefaultPluginManager von pf4j  sollte nicht direkt von den plugins benutzt werden statdessen 
sollten sie um auf andere plugins zuzugreifen den OpenDiabetesPluginManager benutzen

- [ ] Der OpenDiabetesPluginManager instanziiert momentan alle Plugins als singletons, er sollte aber eine art factory bereitstellen um mehrere instanzen eines plugins zu instanzieren

- [x] writeToFile und prepareData können verschoben werden in FileExporter da hier auch die Template methode bereitgestellt wird die die beiden methoden nutzt

- [x] SliceLayoutExporter hat state entries der eliminiert werden kann, wenn man den setEntries deleted und statdessen eine ExportDataToFile(string filepath, list<?> data) einführt (muss dann typechecked sein)

- [x] SourceCodeExporter hat einen state entries der eliminiert werden kann wenn man prepareData im FileExporter generischer eine List<?> zurückgeben lässt und write to file dann eine list<?> nimmt statt einer exportentrylist (listen müssen dann typechecked + gecasted werden)

- [x] Der VaultCSVExporter macht den den VaultExporter nur non abstract kann das jemand erläutern?

**Comment by ocastx** [comment]
@Magnusgaertner was machen wir mit den sachen? Fixxed du das, sollen wir das aufteilen etc?

**Comment by lucasbuschlinger** [comment]
Was sieht am ODVImporter's processImport komisch aus? :D

Zum letzten Punkt: Ich glaube das haben wir/ich gemacht, um das mit den plugin-dependencies zu umgehen, da ja ansonsten der PlotterExporter und der SourceCodeExporter davon erben und somit direkt abhängig sind. Ich glaube wir hatten das mal mit PF4J versucht aber es hat nicht wirklich geklappt...

**Comment by lucasbuschlinger** [comment]
Was macht das Filter Interface? Hat die ML Gruppe sich gemeldet?

**Comment by Magnusgaertner** [comment]
hab euch die mail von der ML Gruppe weitergeleitet und das Interface angefragt

**Comment by Magnusgaertner** [comment]
kann das weg?
```
       /**
         * Constructor.
         *
         * @throws Exception Thrown if the log file could not be written.
         */
        public MedtronicCrawlerImporterImplementation() throws Exception {
            Logger logger = Logger.getLogger("MyLog");
            FileHandler fh;
            SimpleDateFormat formats = new SimpleDateFormat("dd-mm-HHMMSS");

        }
```

und der MedtronicCrawlerImporter hat noch state in Form von start und end date zum Importieren, sollte das nicht beim importieren stateless übergeben werden, irgendwelche ideen wie?

**Comment by lucasbuschlinger** [comment]
Frage für @ocastx 

Start und End Date wäre doch was für die Config...

**Comment by ocastx** [comment]
ja das kann weg und start end date wird eig auch aus der config gelesen

**Comment by Magnusgaertner** [comment]
Ja die Frage war eher ob es in die config gehört, ich würde es auch so lassen ;)

**Comment by ocastx** [comment]
Einzige Möglichkeit wäre nur wenn man es bei dem CrawlerImporter Interface auch mit übergeben könnte. Ist die Frage ob man das möchte da man sonst potentiell immer mehr Parameter bekommt

**Comment by ocastx** [comment]
Das sollte jetzt ja alles durch #140 und #142 resolved worden sein, deswegen closed
